import PptxReformatterClient from './PptxReformatterClient';

export const metadata = {
  title: 'PowerPoint Reformatter | Mays Method Lab',
  description:
    'Upload any messy deck. Get back a Mays-brand-compliant, ADA-accessible version generated by a six-step Claude Haiku pipeline.',
};

/**
 * PowerPoint Reformatter app page. Direct-URL surface plus a card on the
 * Your AI Edge "Apps" sections (faculty + staff). Gated by /apps/layout
 * which redirects unauthenticated visitors to /login.
 */
export default function PptxReformatterPage() {
  return (
    <section className="section">
      <PptxReformatterClient />
    </section>
  );
}
