import 'server-only';
import fs from 'node:fs/promises';
import path from 'node:path';
import { NextResponse } from 'next/server';
import {
  CHEAP_MODEL,
  buildCachedSystem,
  getClient,
  isApiKeyConfigured,
} from '@/lib/evaluation-letters/claude';
import { requireAuth } from '@/lib/evaluation-letters/api-helpers';

export const runtime = 'nodejs';
export const maxDuration = 60;

type ChatMessage = {
  role: 'user' | 'assistant';
  content: string;
};

type Body = {
  messages: ChatMessage[];
};

/**
 * Cache the calendar JSON in module scope. The file is regenerated by
 * scripts/_scrape-academic-calendar.mjs at build time on Render. If the
 * scrape script ever fails to run, we surface a friendly error instead of
 * letting the chatbot fabricate dates.
 */
let cachedCalendar: string | null = null;
async function loadCalendar(): Promise<string> {
  if (cachedCalendar) return cachedCalendar;
  const file = path.join(process.cwd(), 'data', 'sources', 'academic-calendar.json');
  const raw = await fs.readFile(file, 'utf8');
  cachedCalendar = raw;
  return raw;
}

const SYSTEM_PROMPT = `You are the Mays Method Lab Academic Calendar assistant. You answer questions about the Texas A&M University academic calendar for the 2025-2026 academic year (and Fall 2026 where listed).

Hard rules:
1. Answer ONLY from the JSON I provide below. If a date or event is not in the JSON, say so explicitly: "The TAMU Academic Calendar I have access to does not list this directly. The closest related event is X." Do not fabricate dates.
2. Always cite the term and the URL: "Source: TAMU Registrar Academic Calendar (registrar.tamu.edu/academic-calendar)."
3. Refuse off-topic questions politely with: "I only answer questions about the TAMU Academic Calendar."
4. Keep answers tight: 1 to 3 sentences plus an optional bullet list of dates.
5. No "transformative," "exciting," "delve," "leverage," "utilize," or other AI-cheerleader phrasing. Plain Anglo-Saxon English. No em dashes.
6. When the user asks about a relative term like "next semester" or "this term," use the current date (today is 2026-05-02) to map to a specific semester, then answer about that semester.
7. When listing events, render dates exactly as they appear in the JSON.

Format:
- Lead with the answer (the date or the short fact). Then add the term in parentheses.
- One source line at the end.

Calendar JSON (authoritative — do not look elsewhere):
`;

export async function POST(req: Request) {
  const guard = requireAuth(req);
  if (guard) return guard;

  const body = (await req.json().catch(() => null)) as Body | null;
  if (!body?.messages || !Array.isArray(body.messages) || body.messages.length === 0) {
    return NextResponse.json({ error: 'messages array is required.' }, { status: 400 });
  }

  // Cap conversation length so token usage stays sane on long sessions.
  const messages = body.messages.slice(-12).map((m) => ({
    role: m.role === 'assistant' ? ('assistant' as const) : ('user' as const),
    content: String(m.content || '').slice(0, 4000),
  }));
  if (messages.length === 0 || messages[messages.length - 1].role !== 'user') {
    return NextResponse.json({ error: 'Last message must be from the user.' }, { status: 400 });
  }

  let calendarJson: string;
  try {
    calendarJson = await loadCalendar();
  } catch (e) {
    return NextResponse.json(
      {
        error:
          'Calendar source data is missing. Run "node scripts/_scrape-academic-calendar.mjs" to regenerate data/sources/academic-calendar.json.',
      },
      { status: 500 },
    );
  }

  if (!isApiKeyConfigured()) {
    return NextResponse.json({
      message:
        'PLACEHOLDER: ANTHROPIC_API_KEY is not configured. Set a real key in the Render environment to enable answers. The calendar JSON is loaded and ready ' +
        `(${calendarJson.length} bytes).\n\nSource: TAMU Registrar Academic Calendar (registrar.tamu.edu/academic-calendar).`,
    });
  }

  // Static reference (the system prompt + the full calendar JSON) goes into
  // the cacheable block; the per-request instruction is left lightweight.
  const cachedReference = `${SYSTEM_PROMPT}\n${calendarJson}\n`;

  try {
    const client = getClient();
    const reply = await client.messages.create({
      model: CHEAP_MODEL,
      max_tokens: 600,
      system: buildCachedSystem(
        cachedReference,
        'Answer the user from the calendar JSON above. Tight: 1 to 3 sentences plus an optional bullet list. Cite the source line at the end.',
      ),
      messages,
    });
    const text = reply.content
      .filter((b): b is { type: 'text'; text: string } => b.type === 'text')
      .map((b) => b.text)
      .join('')
      .trim();
    return NextResponse.json({ message: text });
  } catch (e) {
    return NextResponse.json(
      { error: e instanceof Error ? e.message : 'Chat failed.' },
      { status: 500 },
    );
  }
}
